### ISSUE TITLE
How to get all the source code files or project: 

### ISSUE THREAD

**Issue by zhangshaoshuai** [aut0/avp64_sw#16]
Hi bro ，thank u for your wonderful sharing 
     I see all the repro things here are about config or build files.
     And actually I just want to know how to write all the SW and how those sw work with avp64. Is there any project or code files can we get and then to read ?

**Comment by aut0** [comment]
Hi,

This is not an issue, but more a question I think.

Unfortunately, I don't understand, what you are looking for.
This `avp64_sw` repository contains different software packages for execution on [avp64](https://github.com/aut0/avp64).
It includes the software source code, build files and configuration files for `avp64`.
You should follow these steps:
1. Build the software packages in `avp64_sw`.
2. Build `avp64`
3. Use the configuration files from `avp64_sw` to execute the software on `avp64`

I hope that helps.

**Comment by zhangshaoshuai** [comment]
Wow ... Thank you ， so soon u replied to me.
it's very nice of you Lukas.
Yeah... Maybe I should finish all the docket things , and then I can find and see some source code...
cause it takes a very long time to finish the xxxx.build_xxx.sh , 
I prefer to building all the kernel stuffs by myself on my machine , this is what I always do. 
Docker is complex and it takes longer...
I hope I can see some source code or projects after the docker building~~ 
Thank u again

**Comment by aut0** [comment]
I see.
You can build the kernel and rootfs yourself if you prefer.
This is the kernel configuration file: https://github.com/aut0/avp64_sw/blob/master/linux/files/avp64_linux_kernel.config
This is the buildroot configuration file: https://github.com/aut0/avp64_sw/blob/master/linux/files/avp64-linux-defconfig
This is the device tree: https://github.com/aut0/avp64_sw/blob/master/linux/files/dt/avp64.dts

**Comment by zhangshaoshuai** [comment]
I have already  found all the config files . but I care more is the ..apps code.
